### ISSUE TITLE
Sample State

### ISSUE THREAD

**Issue by simcha-c** [vanduynamite/MuTube#3]
Hey Paul,

1. Change the renaming of column names in the state. 
2. What is thisVideoLike in the user slice?
3. Videos have many comments? so we should have an array of comment ids in the video slice too. However, that array should include only the top level comments (comments with no parent comment).
4. Every comment should have a children comments array (replies to the comment). 
5. Comments would have likes as well, correct?

Good job!

**Comment by vanduynamite** [comment]
1. Renamed in state:
  a. entities.videos.user_id to uploader_id
  b. Not sure what else there is, can you specify? Certainly some of them have to renamed...

2. thisVideoLike is an indication if this user has liked (1), disliked (-1), or neither (0) on the current video, to be parsed in jBuilder. Maybe there's a better way to do this? I don't want to load "likers_id" and "disliker_ids" onto the video table because practically (though not at this small scale) I assume you wouldn't want to load an array of 2 million likes etc. To make it more granular I suppose I could have two data points that say "video_liked_by_this_user = true" and "video_disliked_by_this_user = false" or something. I made this change for now. Any other ideas?

3. Added array of comment_ids to entities.videos. I initially thought only the comments that were applicable to the current video would be loaded, but after pokedex today I see there's no reason for that.

4. Added array of children_comment_ids to comments slice.

5. Comments will have likes as part of the bonus, yes. I added it now anyways using the same system as in #2 above.
